import {InitialStateInterface} from "./initialState.interface";

export const initialState: InitialStateInterface = {
  familyName: "",
  name: "",
  surname: "",
  wantedPosition: "",
  bussinessTrip: true,
  salary: "",
  currency: "",
  email: "",
  messengers: "",
  busyness: "",
  schedule: "",
  city: "",
  nationality: "",
  dateBirth: "",
  workPeriodFrom0: "",
  workPeriodTo0: "",
  movingToDiffCity: "",
  gender: "",
  family: "",
  tel: "",
  children: "",
  driversLicense: "",
  language: "",
  medicalBook: "",
  addInfo: "",
  links: "",
  telephone: "",
  endingEducation0: "",
  counterEducation: "",
  counterExperience: "",
  responsibility0: "",
  photo: "",
};
